export { default as authClient } from './auth';
export { default as profileClient } from './profile';
export { default as timetableClient } from './timetable';
export { default as ratingClient } from './rating';
export { default as commentClient } from './comment';
export { default as lectureClient } from './lecture';
export { default as starClient } from './star';
export { default as watchClient } from './watch';
export { default as historyClient } from './history';
